### PR TITLE
allow for arbitrary tilejson URLs

### PR DESCRIPTION
**Pull request by talin-trulia**
This is a bit of the opposite of what is asked for in issue #6.

In my workflow, I sometimes need to use reference layers that aren't hosted on mapbox.com. For this, full tileJSON URLs should be used to configure reference-layer.

This patch preserves expected behavior when using a MapBox mapID for configuration.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
I think, there is something wrong in the matching regexp, because my mapID "petrdlouhy.g873n732" doesn't get matched. If I fill it in the "reference layer" box and save, I have string "http://a.tiles.mapbox.com/v3/undefined.jsonp" in the box next time I open the settings.

**Comment by talin-trulia** [comment]
It should work correctly now.

**Comment by PetrDlouhy** [comment]
Hi. I can confirm it works now, as far as I tested.

BTW isn't there some official jsonp for default OSM tiles? I think, it would be suitable default value.

**Comment by springmeyer** [comment]
@PetrDlouhy - thanks for testing. As for as a tilejson for tile.osm.org: not sure but perhaps you could request one be hosted there?

@talin-trulia - Could you also update the docs in the main README for the new functionality and then I will merge?

**Comment by talin-trulia** [comment]
I've updated the readme. I'm not great at documentation, so it may need to be reviewed.

**Comment by ftwillms** [comment]
Also can confirm that this works; tried my own tileJSON URL as well as my own MapBox mapID with success. Tested against the latest in master for TileMill as well as the latest in tilemill-reference-layer (after merge).

**Comment by springmeyer** [comment]
thanks @ftwillms - want to fork this pull and recreate another that will merge cleanly against master. Then I'll hit the button and tag a new release.

**Comment by talin-trulia** [comment]
Sorry, it had been a while, and I didn't realize it no longer merged cleanly.
...for that matter, I can't actually see on github whether this pull request merges cleanly or not.

**Comment by springmeyer** [comment]
yeah, can't auto-merge. Can you rebase?

**Comment by talin-trulia** [comment]
It should merge cleanly now.

**Comment by springmeyer** [comment]
thanks, merged

**Pull request merged**
